name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_enknot }}
          username: ${{ secrets.EC2_USER_enknot }}
          key: ${{ secrets.EC2_SSH_KEY_enknot }}
          script: |
            cd ~/enknot
            git pull origin main
            docker build -t enknot .
            docker stop enknot || true
            docker rm enknot || true
            docker run -d -p 3000:3000 --name enknot --restart always enknot
